-- CREATE DATABASE IF NOT EXISTS fezdb CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
-- CREATE USER IF NOT EXISTS 'fez'@'%' IDENTIFIED BY 'password';
-- GRANT ALL PRIVILEGES ON *.* TO 'fez'@'%';

-- FLUSH PRIVILEGES;
